# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl" do
  version "1.37.0-alpha.0+sylr.4"

  on_macos do
    on_arm do
      url "https://github.com/sylr/kubernetes/releases/download/v#{version}/kubectl-v#{version}-darwin-arm64",
        verified: "github.com/sylr/kubernetes/"
      sha256 "33abe79e7fee39a9cbe760f610f809008fe7971793ba332e1f78891a49102da8"
      binary "kubectl-v1.37.0-alpha.0+sylr.4-darwin-arm64", target: "kubectl"
    end
  end

  name "kubectl"
  desc "kubectl from the sylr/kubernetes release builds"
  homepage "https://github.com/sylr/kubernetes"

  livecheck do
    skip "Auto-generated on release."
  end

  generate_completions_from_executable "kubectl-v1.37.0-alpha.0+sylr.4-darwin-arm64",
    base_name: "kubectl",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    If you have Homebrew's kubernetes-cli formula installed, uninstall or unlink it
    first so this cask can install /opt/homebrew/bin/kubectl:

      brew uninstall kubernetes-cli

    (Linking is skipped when that path is already owned by the formula.)
  EOS
end
