# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl" do
  preflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine",
                 "{{staged_path}}/kubectl-v1.37.1+sylr.1-darwin-arm64"]
    end
  end

  version "1.37.1+sylr.1"

  on_macos do
    on_arm do
      sha256 "db3a1dc121e5163ca59d04fe4baf57fcbfd724b8bfc75d9205490d794706def7"
      url "https://github.com/sylr/kubernetes/releases/download/v#{version}/kubectl-v#{version}-darwin-arm64"
      binary "kubectl-v1.37.1+sylr.1-darwin-arm64", target: "kubectl"
    end
  end

  name "kubectl"
  desc "kubectl from the sylr/kubernetes release builds"
  homepage "https://github.com/sylr/kubernetes"

  livecheck do
    skip "Auto-generated on release."
  end

  generate_completions_from_executable "kubectl-v1.37.1+sylr.1-darwin-arm64",
    base_name: "kubectl",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

  caveats <<~EOS
    If you have Homebrew's kubernetes-cli formula installed, uninstall or unlink it
    first so this cask can install /opt/homebrew/bin/kubectl:

      brew uninstall kubernetes-cli

    (Linking is skipped when that path is already owned by the formula.)
  EOS
end
