# This file was generated by GoReleaser. DO NOT EDIT.
cask "nats" do
  version "0.4.0+sylr.5"

  on_macos do
    on_intel do
      sha256 "1ea22d1d0e2021b5fab66b0951661df934b3dc2d81d186408913475f7c07b25e"
      url "https://github.com/sylr/natscli/releases/download/v#{version}/nats-v#{version}-darwin-amd64.zip",
        verified: "github.com/sylr/natscli/"
      rename "nats-v0.4.0+sylr.5-darwin-amd64/nats", "nats"
    end
    on_arm do
      sha256 "ad17c7cf1a356977757924a5f1a747de5b8d94df7136df0e3cc793152a3c8332"
      url "https://github.com/sylr/natscli/releases/download/v#{version}/nats-v#{version}-darwin-arm64.zip",
        verified: "github.com/sylr/natscli/"
      rename "nats-v0.4.0+sylr.5-darwin-arm64/nats", "nats"
    end
  end

  on_linux do
    on_intel do
      sha256 "3807db74f7625def2265488d81c44e73352dd38227d3120128b20f304993ffa6"
      url "https://github.com/sylr/natscli/releases/download/v#{version}/nats-v#{version}-linux-amd64.zip",
        verified: "github.com/sylr/natscli/"
      rename "nats-v0.4.0+sylr.5-linux-amd64/nats", "nats"
    end
    on_arm do
      sha256 "7294e96adb0e0a6ca4c863cfab42d26e52186ddb17552580a8dcdce64559308a"
      url "https://github.com/sylr/natscli/releases/download/v#{version}/nats-v#{version}-linux-arm64.zip",
        verified: "github.com/sylr/natscli/"
      rename "nats-v0.4.0+sylr.5-linux-arm64/nats", "nats"
    end
  end

  name "nats"
  desc "NATS utility"
  homepage "https://github.com/sylr/natscli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nats"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
      nats = staged_path.glob("nats-*/nats").first
      nats ||= staged_path/"nats"
      raise "nats binary not found in #{staged_path}" unless nats.exist?

      executable = nats.to_s
      %i[bash zsh fish].each do |shell|
        env = { "SHELL" => shell.to_s }
        param = ::Utils::ShellCompletion.completion_shell_parameter(:cobra, shell, executable, env)
        out = ::Utils::ShellCompletion.generate_completion_output([executable], param, env)
        path = case shell
        when :bash
          ::Cask::Artifact::BashCompletion.new(cask, "nats").resolve_target("nats")
        when :zsh
          ::Cask::Artifact::ZshCompletion.new(cask, "nats").resolve_target("nats")
        when :fish
          ::Cask::Artifact::FishCompletion.new(cask, "nats").resolve_target("nats")
        end
        path.dirname.mkpath
        path.write(out)
      end
    end
  end

  uninstall_preflight do
    if OS.mac?
      %i[bash zsh fish].each do |shell|
        path = case shell
        when :bash
          ::Cask::Artifact::BashCompletion.new(cask, "nats").resolve_target("nats")
        when :zsh
          ::Cask::Artifact::ZshCompletion.new(cask, "nats").resolve_target("nats")
        when :fish
          ::Cask::Artifact::FishCompletion.new(cask, "nats").resolve_target("nats")
        end
        ::Cask::Utils.gain_permissions_remove(path) if path.exist?
      end
    end
  end

  # No zap stanza required

end
