# This file was generated by GoReleaser. DO NOT EDIT.
cask "nats" do
  version "0.4.0+sylr.4"

  on_macos do
    on_intel do
      sha256 "11e810c5954db4e54d2785f14494573742dae81790eaebc972efe1d544bf8654"
      url "https://github.com/sylr/natscli/releases/download/v#{version}/nats-v#{version}-darwin-amd64.zip",
        verified: "github.com/sylr/natscli/"
      rename "nats-v0.4.0+sylr.4-darwin-amd64/nats", "nats"
    end
    on_arm do
      sha256 "f909756e805b85bdd164bd93f82216b9cd556fd7be43df4b64cf5bf203b5efb0"
      url "https://github.com/sylr/natscli/releases/download/v#{version}/nats-v#{version}-darwin-arm64.zip",
        verified: "github.com/sylr/natscli/"
      rename "nats-v0.4.0+sylr.4-darwin-arm64/nats", "nats"
    end
  end

  on_linux do
    on_intel do
      sha256 "35d11bc32ed6bc13f24ddf423004b92103a9942367dc135eb039adfc98eac2a3"
      url "https://github.com/sylr/natscli/releases/download/v#{version}/nats-v#{version}-linux-amd64.zip",
        verified: "github.com/sylr/natscli/"
      rename "nats-v0.4.0+sylr.4-linux-amd64/nats", "nats"
    end
    on_arm do
      sha256 "c1b9abf911a4d28faa38de0de28489e7a963160bbc1f50906a347414dbca7292"
      url "https://github.com/sylr/natscli/releases/download/v#{version}/nats-v#{version}-linux-arm64.zip",
        verified: "github.com/sylr/natscli/"
      rename "nats-v0.4.0+sylr.4-linux-arm64/nats", "nats"
    end
  end

  name "nats"
  desc "NATS utility"
  homepage "https://github.com/sylr/natscli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nats"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
      nats = staged_path.glob("nats-*/nats").first
      nats ||= staged_path/"nats"
      raise "nats binary not found in #{staged_path}" unless nats.exist?

      executable = nats.to_s
      %i[bash zsh fish].each do |shell|
        env = { "SHELL" => shell.to_s }
        param = ::Utils::ShellCompletion.completion_shell_parameter(:cobra, shell, executable, env)
        out = ::Utils::ShellCompletion.generate_completion_output([executable], param, env)
        path = case shell
        when :bash
          ::Cask::Artifact::BashCompletion.new(cask, "nats").resolve_target("nats")
        when :zsh
          ::Cask::Artifact::ZshCompletion.new(cask, "nats").resolve_target("nats")
        when :fish
          ::Cask::Artifact::FishCompletion.new(cask, "nats").resolve_target("nats")
        end
        path.dirname.mkpath
        path.write(out)
      end
    end
  end

  uninstall_preflight do
    if OS.mac?
      %i[bash zsh fish].each do |shell|
        path = case shell
        when :bash
          ::Cask::Artifact::BashCompletion.new(cask, "nats").resolve_target("nats")
        when :zsh
          ::Cask::Artifact::ZshCompletion.new(cask, "nats").resolve_target("nats")
        when :fish
          ::Cask::Artifact::FishCompletion.new(cask, "nats").resolve_target("nats")
        end
        ::Cask::Utils.gain_permissions_remove(path) if path.exist?
      end
    end
  end

  # No zap stanza required

end
