# This file was generated by GoReleaser. DO NOT EDIT.
cask "nats" do
  version "0.4.0+sylr.6"

  on_macos do
    on_intel do
      sha256 "4497894e6bdb98cafc78ded1dbda4116fe7e79167d43406a589f693a521e14cb"
      url "https://github.com/sylr/natscli/releases/download/v#{version}/nats-v#{version}-darwin-amd64.zip",
        verified: "github.com/sylr/natscli/"
      rename "nats-v0.4.0+sylr.6-darwin-amd64/nats", "nats"
    end
    on_arm do
      sha256 "0e9083f6b2f5d0ddf4a0052582f9a83c3796a8f36bebc4692b4168481d851d38"
      url "https://github.com/sylr/natscli/releases/download/v#{version}/nats-v#{version}-darwin-arm64.zip",
        verified: "github.com/sylr/natscli/"
      rename "nats-v0.4.0+sylr.6-darwin-arm64/nats", "nats"
    end
  end

  on_linux do
    on_intel do
      sha256 "3b92f64d4cd3d8dc9ab743570434077cf9f71e8be8e688de5270b3be602afcf6"
      url "https://github.com/sylr/natscli/releases/download/v#{version}/nats-v#{version}-linux-amd64.zip",
        verified: "github.com/sylr/natscli/"
      rename "nats-v0.4.0+sylr.6-linux-amd64/nats", "nats"
    end
    on_arm do
      sha256 "b8ad941668e0da668162c3880c1e18d36b56c3b3c74d9dcfcd7970416f69a019"
      url "https://github.com/sylr/natscli/releases/download/v#{version}/nats-v#{version}-linux-arm64.zip",
        verified: "github.com/sylr/natscli/"
      rename "nats-v0.4.0+sylr.6-linux-arm64/nats", "nats"
    end
  end

  name "nats"
  desc "NATS utility"
  homepage "https://github.com/sylr/natscli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nats"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
      nats = staged_path.glob("nats-*/nats").first
      nats ||= staged_path/"nats"
      raise "nats binary not found in #{staged_path}" unless nats.exist?

      executable = nats.to_s
      %i[bash zsh fish].each do |shell|
        env = { "SHELL" => shell.to_s }
        param = ::Utils::ShellCompletion.completion_shell_parameter(:cobra, shell, executable, env)
        out = ::Utils::ShellCompletion.generate_completion_output([executable], param, env)
        path = case shell
        when :bash
          ::Cask::Artifact::BashCompletion.new(cask, "nats").resolve_target("nats")
        when :zsh
          ::Cask::Artifact::ZshCompletion.new(cask, "nats").resolve_target("nats")
        when :fish
          ::Cask::Artifact::FishCompletion.new(cask, "nats").resolve_target("nats")
        end
        path.dirname.mkpath
        path.write(out)
      end
    end
  end

  uninstall_preflight do
    if OS.mac?
      %i[bash zsh fish].each do |shell|
        path = case shell
        when :bash
          ::Cask::Artifact::BashCompletion.new(cask, "nats").resolve_target("nats")
        when :zsh
          ::Cask::Artifact::ZshCompletion.new(cask, "nats").resolve_target("nats")
        when :fish
          ::Cask::Artifact::FishCompletion.new(cask, "nats").resolve_target("nats")
        end
        ::Cask::Utils.gain_permissions_remove(path) if path.exist?
      end
    end
  end

  # No zap stanza required

end
