# This file was generated by GoReleaser. DO NOT EDIT.
cask "op-cached" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/op-cached"], must_succeed: false
  end

  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "ba6a06e049d9f5e29ae3990e9aafdc26f85e91a5d2df0b433e27428eb3d6ef5e"
      url "https://github.com/sylr/op-cached/releases/download/v#{version}/op-cached_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8422ee305d0a001910f1a13ce02e4cac5e60c3289c6cfd095ea7537cf93bf777"
      url "https://github.com/sylr/op-cached/releases/download/v#{version}/op-cached_v#{version}_darwin_amd64.tar.gz"
    end
  end

  name "op-cached"
  desc "Cache 1Password CLI secret reads in the macOS keychain"
  homepage "https://github.com/sylr/op-cached"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "op-cached"

  # No zap stanza required

  caveats <<~EOS
    op-cached needs the 1Password CLI (op) on PATH.
  EOS
end
