# This file was generated by GoReleaser. DO NOT EDIT.
cask "op-cached" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "7356ca54653653c8fb4f168deaf35ca969a70b2432fc2a2ceb62fa692d7a06d1"
      url "https://github.com/sylr/op-cached/releases/download/v#{version}/op-cached_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c72bdeda4d3809e3796c0c8c526a2809b9f201179ac496e2b48e97b19117449a"
      url "https://github.com/sylr/op-cached/releases/download/v#{version}/op-cached_v#{version}_darwin_amd64.tar.gz"
    end
  end

  name "op-cached"
  desc "Cache 1Password CLI secret reads in the macOS keychain"
  homepage "https://github.com/sylr/op-cached"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "op-cached"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/op-cached"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    op-cached needs the 1Password CLI (op) on PATH.
  EOS
end
