# This file was generated by GoReleaser. DO NOT EDIT.
cask "op-cached" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "9c95e0aefb11821561212c48f17fe4283c3a05255f0b88d52a6a3a27cd6e40a2"
      url "https://github.com/sylr/op-cached/releases/download/v#{version}/op-cached_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "469dc521346a4506f0cb53d8f5a32371a47490047f1b2d2148842874a6a2158f"
      url "https://github.com/sylr/op-cached/releases/download/v#{version}/op-cached_v#{version}_darwin_amd64.tar.gz"
    end
  end

  name "op-cached"
  desc "Cache 1Password CLI secret reads in the macOS keychain"
  homepage "https://github.com/sylr/op-cached"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "op-cached"

  # No zap stanza required

  caveats <<~EOS
    op-cached needs the 1Password CLI (op) on PATH.
  EOS
end
